## Hosts ##
endpoint:
  losore: https://losoreregisteret.ppe.brreg.no/registerinfo
  ektepakt: https://ektepaktregisteret.ppe.brreg.no/ektepakt

## Maskinporten ##
issuer:
audience: https://test.maskinporten.no/
token.endpoint: https://test.maskinporten.no/token
scope: brreg:losore/tlg

keystore:
  file:
  password:
  type:
  alias:
  alias.password:
