## Hosts ##
endpoint:
  url: https://losoreregisteret.ppe.brreg.no/registerinfo

## Maskinporten ##
issuer:
audience: https://ver2.maskinporten.no/
token.endpoint: https://ver2.maskinporten.no/token
scope: brreg:losore/tlg

keystore:
  file:
  password:
  type:
  alias:
  alias.password:
