## System.properties ##
server:
  port: 8086
  shutdown: graceful
management:
  server:
    port: 8081

logging:
  level:
    root: INFO

## Hosts ##
endpoint:
  url: <losore-tlg-url>

##Se dokumentasjon her for hvordan man får tak i klient id og scope: https://brreg.github.io/docs/apidokumentasjon/losoreregisteret/itu-utt/mp-integrasjonsveiledning/
##Client får man ved forespørsel fra fra difi
##Scope får man fra docs eller brsys

issuer: <client_id>
audience: https://ver2.maskinporten.no/
token.endpoint: https://ver2.maskinporten.no/token
scope: <scope>

keystore:
  file: <path to keystore>
  password: <keystore password>
  type: <type>
  alias: <keystore alias>
  alias.password: <alias password>

