## Hosts ##
endpoint:
  url: https://losore-tlg-api.apps.ocp-prd.regsys.brreg.no

## maskinporten url ##
jwt:
  audience: https://oidc-prod.difi.no/idporten-oidc-provider/
  endpoint: https://oidc-prod.difi.no/idporten-oidc-provider/token
