## Hosts ##
endpoint:
  url: https://losoreregisteret.brreg.no/registerinfo

## Maskinporten ##
issuer: <client_id>
audience: https://oidc-prod.difi.no/idporten-oidc-provider/
token.endpoint: https://oidc-prod.difi.no/idporten-oidc-provider/token
scope: <scope>

keystore:
  file: <path to keystore>
  password: <keystore password>
  alias: <keystore alias>
    password: <alias password>
